# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Thu Nov 14 12:54:47 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from pokemon_display import PokemonDisplay

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 640)
        MainWindow.setMinimumSize(QtCore.QSize(770, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBoxConnection = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxConnection.sizePolicy().hasHeightForWidth())
        self.groupBoxConnection.setSizePolicy(sizePolicy)
        self.groupBoxConnection.setObjectName("groupBoxConnection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxConnection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBoxConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConnect.sizePolicy().hasHeightForWidth())
        self.pushButtonConnect.setSizePolicy(sizePolicy)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayout_2.addWidget(self.pushButtonConnect, 0, 1, 1, 1)
        self.labelUpdateDelay = QtWidgets.QLabel(self.groupBoxConnection)
        self.labelUpdateDelay.setObjectName("labelUpdateDelay")
        self.gridLayout_2.addWidget(self.labelUpdateDelay, 1, 0, 1, 1)
        self.labelStatus = QtWidgets.QLabel(self.groupBoxConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout_2.addWidget(self.labelStatus, 1, 2, 1, 1)
        self.comboBoxGameSelection = QtWidgets.QComboBox(self.groupBoxConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxGameSelection.sizePolicy().hasHeightForWidth())
        self.comboBoxGameSelection.setSizePolicy(sizePolicy)
        self.comboBoxGameSelection.setObjectName("comboBoxGameSelection")
        self.comboBoxGameSelection.addItem("")
        self.comboBoxGameSelection.addItem("")
        self.comboBoxGameSelection.addItem("")
        self.comboBoxGameSelection.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxGameSelection, 0, 0, 1, 1)
        self.doubleSpinBoxDelay = QtWidgets.QDoubleSpinBox(self.groupBoxConnection)
        self.doubleSpinBoxDelay.setEnabled(False)
        self.doubleSpinBoxDelay.setMinimum(0.5)
        self.doubleSpinBoxDelay.setMaximum(2.0)
        self.doubleSpinBoxDelay.setObjectName("doubleSpinBoxDelay")
        self.gridLayout_2.addWidget(self.doubleSpinBoxDelay, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxConnection, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGen6 = QtWidgets.QWidget()
        self.tabGen6.setObjectName("tabGen6")
        self.gridLayout = QtWidgets.QGridLayout(self.tabGen6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidgetGen6 = QtWidgets.QTabWidget(self.tabGen6)
        self.tabWidgetGen6.setObjectName("tabWidgetGen6")
        self.tabMain6 = QtWidgets.QWidget()
        self.tabMain6.setObjectName("tabMain6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tabMain6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.comboBoxMainIndex6 = QtWidgets.QComboBox(self.tabMain6)
        self.comboBoxMainIndex6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMainIndex6.sizePolicy().hasHeightForWidth())
        self.comboBoxMainIndex6.setSizePolicy(sizePolicy)
        self.comboBoxMainIndex6.setObjectName("comboBoxMainIndex6")
        self.comboBoxMainIndex6.addItem("")
        self.comboBoxMainIndex6.addItem("")
        self.comboBoxMainIndex6.addItem("")
        self.comboBoxMainIndex6.addItem("")
        self.comboBoxMainIndex6.addItem("")
        self.comboBoxMainIndex6.addItem("")
        self.comboBoxMainIndex6.addItem("")
        self.gridLayout_13.addWidget(self.comboBoxMainIndex6, 0, 0, 1, 1)
        self.groupBoxMainRNG6 = QtWidgets.QGroupBox(self.tabMain6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMainRNG6.sizePolicy().hasHeightForWidth())
        self.groupBoxMainRNG6.setSizePolicy(sizePolicy)
        self.groupBoxMainRNG6.setObjectName("groupBoxMainRNG6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxMainRNG6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEditFrame6 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFrame6.sizePolicy().hasHeightForWidth())
        self.lineEditFrame6.setSizePolicy(sizePolicy)
        self.lineEditFrame6.setReadOnly(True)
        self.lineEditFrame6.setObjectName("lineEditFrame6")
        self.gridLayout_11.addWidget(self.lineEditFrame6, 3, 2, 1, 2)
        self.labelTiny2 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelTiny2.setObjectName("labelTiny2")
        self.gridLayout_11.addWidget(self.labelTiny2, 5, 2, 1, 1)
        self.labelTiny0 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelTiny0.setObjectName("labelTiny0")
        self.gridLayout_11.addWidget(self.labelTiny0, 6, 2, 1, 1)
        self.lineEditInitialSeed6 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInitialSeed6.sizePolicy().hasHeightForWidth())
        self.lineEditInitialSeed6.setSizePolicy(sizePolicy)
        self.lineEditInitialSeed6.setMaxLength(8)
        self.lineEditInitialSeed6.setReadOnly(True)
        self.lineEditInitialSeed6.setObjectName("lineEditInitialSeed6")
        self.gridLayout_11.addWidget(self.lineEditInitialSeed6, 1, 2, 1, 2)
        self.labelTiny3 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelTiny3.setObjectName("labelTiny3")
        self.gridLayout_11.addWidget(self.labelTiny3, 5, 0, 1, 1)
        self.labelTiny1 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelTiny1.setObjectName("labelTiny1")
        self.gridLayout_11.addWidget(self.labelTiny1, 6, 0, 1, 1)
        self.labelMainCurrentSeed6 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelMainCurrentSeed6.setObjectName("labelMainCurrentSeed6")
        self.gridLayout_11.addWidget(self.labelMainCurrentSeed6, 2, 0, 1, 2)
        self.lineEditCurrentSeed6 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCurrentSeed6.sizePolicy().hasHeightForWidth())
        self.lineEditCurrentSeed6.setSizePolicy(sizePolicy)
        self.lineEditCurrentSeed6.setMaxLength(16)
        self.lineEditCurrentSeed6.setReadOnly(True)
        self.lineEditCurrentSeed6.setObjectName("lineEditCurrentSeed6")
        self.gridLayout_11.addWidget(self.lineEditCurrentSeed6, 2, 2, 1, 2)
        self.lineEditTiny2 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        self.lineEditTiny2.setObjectName("lineEditTiny2")
        self.gridLayout_11.addWidget(self.lineEditTiny2, 5, 3, 1, 1)
        self.lineEditTiny1 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        self.lineEditTiny1.setObjectName("lineEditTiny1")
        self.gridLayout_11.addWidget(self.lineEditTiny1, 6, 1, 1, 1)
        self.lineEditTiny3 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        self.lineEditTiny3.setObjectName("lineEditTiny3")
        self.gridLayout_11.addWidget(self.lineEditTiny3, 5, 1, 1, 1)
        self.labelMainInitialSeed6 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelMainInitialSeed6.setObjectName("labelMainInitialSeed6")
        self.gridLayout_11.addWidget(self.labelMainInitialSeed6, 1, 0, 1, 2)
        self.labelMainFrame6 = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelMainFrame6.setObjectName("labelMainFrame6")
        self.gridLayout_11.addWidget(self.labelMainFrame6, 3, 0, 1, 1)
        self.lineEditTiny0 = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        self.lineEditTiny0.setObjectName("lineEditTiny0")
        self.gridLayout_11.addWidget(self.lineEditTiny0, 6, 3, 1, 1)
        self.pushButtonMainUpdate6 = QtWidgets.QPushButton(self.groupBoxMainRNG6)
        self.pushButtonMainUpdate6.setEnabled(False)
        self.pushButtonMainUpdate6.setObjectName("pushButtonMainUpdate6")
        self.gridLayout_11.addWidget(self.pushButtonMainUpdate6, 0, 0, 1, 4)
        self.labelSaveVariable = QtWidgets.QLabel(self.groupBoxMainRNG6)
        self.labelSaveVariable.setObjectName("labelSaveVariable")
        self.gridLayout_11.addWidget(self.labelSaveVariable, 4, 0, 1, 1)
        self.lineEditSaveVariable = QtWidgets.QLineEdit(self.groupBoxMainRNG6)
        self.lineEditSaveVariable.setReadOnly(True)
        self.lineEditSaveVariable.setObjectName("lineEditSaveVariable")
        self.gridLayout_11.addWidget(self.lineEditSaveVariable, 4, 2, 1, 2)
        self.gridLayout_13.addWidget(self.groupBoxMainRNG6, 0, 1, 2, 1)
        self.mainPokemon6 = PokemonDisplay(self.tabMain6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPokemon6.sizePolicy().hasHeightForWidth())
        self.mainPokemon6.setSizePolicy(sizePolicy)
        self.mainPokemon6.setObjectName("mainPokemon6")
        self.gridLayout_13.addWidget(self.mainPokemon6, 1, 0, 1, 1)
        self.tabWidgetGen6.addTab(self.tabMain6, "")
        self.tabEgg6 = QtWidgets.QWidget()
        self.tabEgg6.setObjectName("tabEgg6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tabEgg6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.eggParent1_6 = PokemonDisplay(self.tabEgg6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eggParent1_6.sizePolicy().hasHeightForWidth())
        self.eggParent1_6.setSizePolicy(sizePolicy)
        self.eggParent1_6.setObjectName("eggParent1_6")
        self.gridLayout_15.addWidget(self.eggParent1_6, 0, 0, 1, 1)
        self.eggParent2_6 = PokemonDisplay(self.tabEgg6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eggParent2_6.sizePolicy().hasHeightForWidth())
        self.eggParent2_6.setSizePolicy(sizePolicy)
        self.eggParent2_6.setObjectName("eggParent2_6")
        self.gridLayout_15.addWidget(self.eggParent2_6, 0, 1, 1, 1)
        self.groupBoxEggRNG6 = QtWidgets.QGroupBox(self.tabEgg6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEggRNG6.sizePolicy().hasHeightForWidth())
        self.groupBoxEggRNG6.setSizePolicy(sizePolicy)
        self.groupBoxEggRNG6.setObjectName("groupBoxEggRNG6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBoxEggRNG6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.labelEggReady6 = QtWidgets.QLabel(self.groupBoxEggRNG6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEggReady6.sizePolicy().hasHeightForWidth())
        self.labelEggReady6.setSizePolicy(sizePolicy)
        self.labelEggReady6.setObjectName("labelEggReady6")
        self.gridLayout_14.addWidget(self.labelEggReady6, 1, 0, 1, 1)
        self.labelEggReadyStatus6 = QtWidgets.QLabel(self.groupBoxEggRNG6)
        self.labelEggReadyStatus6.setObjectName("labelEggReadyStatus6")
        self.gridLayout_14.addWidget(self.labelEggReadyStatus6, 1, 1, 1, 1)
        self.lineEditEggSeed0_6 = QtWidgets.QLineEdit(self.groupBoxEggRNG6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed0_6.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed0_6.setSizePolicy(sizePolicy)
        self.lineEditEggSeed0_6.setMaxLength(8)
        self.lineEditEggSeed0_6.setReadOnly(True)
        self.lineEditEggSeed0_6.setObjectName("lineEditEggSeed0_6")
        self.gridLayout_14.addWidget(self.lineEditEggSeed0_6, 3, 1, 1, 1)
        self.pushButtonEggUpdate6 = QtWidgets.QPushButton(self.groupBoxEggRNG6)
        self.pushButtonEggUpdate6.setEnabled(False)
        self.pushButtonEggUpdate6.setObjectName("pushButtonEggUpdate6")
        self.gridLayout_14.addWidget(self.pushButtonEggUpdate6, 0, 0, 1, 2)
        self.labelEggSeed0_6 = QtWidgets.QLabel(self.groupBoxEggRNG6)
        self.labelEggSeed0_6.setObjectName("labelEggSeed0_6")
        self.gridLayout_14.addWidget(self.labelEggSeed0_6, 3, 0, 1, 1)
        self.labelEggSeed1_6 = QtWidgets.QLabel(self.groupBoxEggRNG6)
        self.labelEggSeed1_6.setObjectName("labelEggSeed1_6")
        self.gridLayout_14.addWidget(self.labelEggSeed1_6, 2, 0, 1, 1)
        self.lineEditEggSeed1_6 = QtWidgets.QLineEdit(self.groupBoxEggRNG6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed1_6.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed1_6.setSizePolicy(sizePolicy)
        self.lineEditEggSeed1_6.setMaxLength(8)
        self.lineEditEggSeed1_6.setReadOnly(True)
        self.lineEditEggSeed1_6.setObjectName("lineEditEggSeed1_6")
        self.gridLayout_14.addWidget(self.lineEditEggSeed1_6, 2, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBoxEggRNG6, 0, 2, 1, 1)
        self.tabWidgetGen6.addTab(self.tabEgg6, "")
        self.gridLayout.addWidget(self.tabWidgetGen6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGen6, "")
        self.tabGen7 = QtWidgets.QWidget()
        self.tabGen7.setEnabled(False)
        self.tabGen7.setObjectName("tabGen7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabGen7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidgetGen7 = QtWidgets.QTabWidget(self.tabGen7)
        self.tabWidgetGen7.setObjectName("tabWidgetGen7")
        self.tabMain7 = QtWidgets.QWidget()
        self.tabMain7.setObjectName("tabMain7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabMain7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBoxMainIndex7 = QtWidgets.QComboBox(self.tabMain7)
        self.comboBoxMainIndex7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMainIndex7.sizePolicy().hasHeightForWidth())
        self.comboBoxMainIndex7.setSizePolicy(sizePolicy)
        self.comboBoxMainIndex7.setObjectName("comboBoxMainIndex7")
        self.comboBoxMainIndex7.addItem("")
        self.comboBoxMainIndex7.addItem("")
        self.comboBoxMainIndex7.addItem("")
        self.comboBoxMainIndex7.addItem("")
        self.comboBoxMainIndex7.addItem("")
        self.comboBoxMainIndex7.addItem("")
        self.comboBoxMainIndex7.addItem("")
        self.gridLayout_7.addWidget(self.comboBoxMainIndex7, 0, 0, 1, 1)
        self.groupBoxMainRNG7 = QtWidgets.QGroupBox(self.tabMain7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMainRNG7.sizePolicy().hasHeightForWidth())
        self.groupBoxMainRNG7.setSizePolicy(sizePolicy)
        self.groupBoxMainRNG7.setObjectName("groupBoxMainRNG7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxMainRNG7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelMainInitialSeed7 = QtWidgets.QLabel(self.groupBoxMainRNG7)
        self.labelMainInitialSeed7.setObjectName("labelMainInitialSeed7")
        self.gridLayout_3.addWidget(self.labelMainInitialSeed7, 1, 0, 1, 1)
        self.lineEditInitialSeed7 = QtWidgets.QLineEdit(self.groupBoxMainRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInitialSeed7.sizePolicy().hasHeightForWidth())
        self.lineEditInitialSeed7.setSizePolicy(sizePolicy)
        self.lineEditInitialSeed7.setMaxLength(8)
        self.lineEditInitialSeed7.setReadOnly(True)
        self.lineEditInitialSeed7.setObjectName("lineEditInitialSeed7")
        self.gridLayout_3.addWidget(self.lineEditInitialSeed7, 1, 1, 1, 1)
        self.labelMainCurrentSeed7 = QtWidgets.QLabel(self.groupBoxMainRNG7)
        self.labelMainCurrentSeed7.setObjectName("labelMainCurrentSeed7")
        self.gridLayout_3.addWidget(self.labelMainCurrentSeed7, 2, 0, 1, 1)
        self.lineEditCurrentSeed7 = QtWidgets.QLineEdit(self.groupBoxMainRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCurrentSeed7.sizePolicy().hasHeightForWidth())
        self.lineEditCurrentSeed7.setSizePolicy(sizePolicy)
        self.lineEditCurrentSeed7.setMaxLength(16)
        self.lineEditCurrentSeed7.setReadOnly(True)
        self.lineEditCurrentSeed7.setObjectName("lineEditCurrentSeed7")
        self.gridLayout_3.addWidget(self.lineEditCurrentSeed7, 2, 1, 1, 1)
        self.labelMainFrame7 = QtWidgets.QLabel(self.groupBoxMainRNG7)
        self.labelMainFrame7.setObjectName("labelMainFrame7")
        self.gridLayout_3.addWidget(self.labelMainFrame7, 3, 0, 1, 1)
        self.lineEditFrame7 = QtWidgets.QLineEdit(self.groupBoxMainRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFrame7.sizePolicy().hasHeightForWidth())
        self.lineEditFrame7.setSizePolicy(sizePolicy)
        self.lineEditFrame7.setReadOnly(True)
        self.lineEditFrame7.setObjectName("lineEditFrame7")
        self.gridLayout_3.addWidget(self.lineEditFrame7, 3, 1, 1, 1)
        self.pushButtonMainUpdate7 = QtWidgets.QPushButton(self.groupBoxMainRNG7)
        self.pushButtonMainUpdate7.setEnabled(False)
        self.pushButtonMainUpdate7.setObjectName("pushButtonMainUpdate7")
        self.gridLayout_3.addWidget(self.pushButtonMainUpdate7, 0, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBoxMainRNG7, 0, 1, 2, 1)
        self.mainPokemon7 = PokemonDisplay(self.tabMain7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPokemon7.sizePolicy().hasHeightForWidth())
        self.mainPokemon7.setSizePolicy(sizePolicy)
        self.mainPokemon7.setObjectName("mainPokemon7")
        self.gridLayout_7.addWidget(self.mainPokemon7, 1, 0, 1, 1)
        self.tabWidgetGen7.addTab(self.tabMain7, "")
        self.tabEgg7 = QtWidgets.QWidget()
        self.tabEgg7.setObjectName("tabEgg7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabEgg7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBoxEggRNG7 = QtWidgets.QGroupBox(self.tabEgg7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEggRNG7.sizePolicy().hasHeightForWidth())
        self.groupBoxEggRNG7.setSizePolicy(sizePolicy)
        self.groupBoxEggRNG7.setObjectName("groupBoxEggRNG7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxEggRNG7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonEggUpdate7 = QtWidgets.QPushButton(self.groupBoxEggRNG7)
        self.pushButtonEggUpdate7.setEnabled(False)
        self.pushButtonEggUpdate7.setObjectName("pushButtonEggUpdate7")
        self.gridLayout_4.addWidget(self.pushButtonEggUpdate7, 0, 0, 1, 2)
        self.labelEggReady7 = QtWidgets.QLabel(self.groupBoxEggRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEggReady7.sizePolicy().hasHeightForWidth())
        self.labelEggReady7.setSizePolicy(sizePolicy)
        self.labelEggReady7.setObjectName("labelEggReady7")
        self.gridLayout_4.addWidget(self.labelEggReady7, 1, 0, 1, 1)
        self.labelEggReadyStatus7 = QtWidgets.QLabel(self.groupBoxEggRNG7)
        self.labelEggReadyStatus7.setObjectName("labelEggReadyStatus7")
        self.gridLayout_4.addWidget(self.labelEggReadyStatus7, 1, 1, 1, 1)
        self.labelEggSeed3_7 = QtWidgets.QLabel(self.groupBoxEggRNG7)
        self.labelEggSeed3_7.setObjectName("labelEggSeed3_7")
        self.gridLayout_4.addWidget(self.labelEggSeed3_7, 2, 0, 1, 1)
        self.lineEditEggSeed3_7 = QtWidgets.QLineEdit(self.groupBoxEggRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed3_7.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed3_7.setSizePolicy(sizePolicy)
        self.lineEditEggSeed3_7.setMaxLength(8)
        self.lineEditEggSeed3_7.setReadOnly(True)
        self.lineEditEggSeed3_7.setObjectName("lineEditEggSeed3_7")
        self.gridLayout_4.addWidget(self.lineEditEggSeed3_7, 2, 1, 1, 1)
        self.labelEggSeed2_7 = QtWidgets.QLabel(self.groupBoxEggRNG7)
        self.labelEggSeed2_7.setObjectName("labelEggSeed2_7")
        self.gridLayout_4.addWidget(self.labelEggSeed2_7, 3, 0, 1, 1)
        self.lineEditEggSeed2_7 = QtWidgets.QLineEdit(self.groupBoxEggRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed2_7.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed2_7.setSizePolicy(sizePolicy)
        self.lineEditEggSeed2_7.setMaxLength(8)
        self.lineEditEggSeed2_7.setReadOnly(True)
        self.lineEditEggSeed2_7.setObjectName("lineEditEggSeed2_7")
        self.gridLayout_4.addWidget(self.lineEditEggSeed2_7, 3, 1, 1, 1)
        self.labelEggSeed1_7 = QtWidgets.QLabel(self.groupBoxEggRNG7)
        self.labelEggSeed1_7.setObjectName("labelEggSeed1_7")
        self.gridLayout_4.addWidget(self.labelEggSeed1_7, 4, 0, 1, 1)
        self.lineEditEggSeed1_7 = QtWidgets.QLineEdit(self.groupBoxEggRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed1_7.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed1_7.setSizePolicy(sizePolicy)
        self.lineEditEggSeed1_7.setMaxLength(8)
        self.lineEditEggSeed1_7.setReadOnly(True)
        self.lineEditEggSeed1_7.setObjectName("lineEditEggSeed1_7")
        self.gridLayout_4.addWidget(self.lineEditEggSeed1_7, 4, 1, 1, 1)
        self.labelEggSeed0_7 = QtWidgets.QLabel(self.groupBoxEggRNG7)
        self.labelEggSeed0_7.setObjectName("labelEggSeed0_7")
        self.gridLayout_4.addWidget(self.labelEggSeed0_7, 5, 0, 1, 1)
        self.lineEditEggSeed0_7 = QtWidgets.QLineEdit(self.groupBoxEggRNG7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed0_7.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed0_7.setSizePolicy(sizePolicy)
        self.lineEditEggSeed0_7.setMaxLength(8)
        self.lineEditEggSeed0_7.setReadOnly(True)
        self.lineEditEggSeed0_7.setObjectName("lineEditEggSeed0_7")
        self.gridLayout_4.addWidget(self.lineEditEggSeed0_7, 5, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBoxEggRNG7, 0, 2, 2, 1)
        self.eggParent1_7 = PokemonDisplay(self.tabEgg7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eggParent1_7.sizePolicy().hasHeightForWidth())
        self.eggParent1_7.setSizePolicy(sizePolicy)
        self.eggParent1_7.setObjectName("eggParent1_7")
        self.gridLayout_6.addWidget(self.eggParent1_7, 0, 0, 2, 1)
        self.eggParent2_7 = PokemonDisplay(self.tabEgg7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eggParent2_7.sizePolicy().hasHeightForWidth())
        self.eggParent2_7.setSizePolicy(sizePolicy)
        self.eggParent2_7.setObjectName("eggParent2_7")
        self.gridLayout_6.addWidget(self.eggParent2_7, 0, 1, 2, 1)
        self.tabWidgetGen7.addTab(self.tabEgg7, "")
        self.tabSOS = QtWidgets.QWidget()
        self.tabSOS.setObjectName("tabSOS")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabSOS)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBoxSOSIndex = QtWidgets.QComboBox(self.tabSOS)
        self.comboBoxSOSIndex.setEnabled(False)
        self.comboBoxSOSIndex.setObjectName("comboBoxSOSIndex")
        self.comboBoxSOSIndex.addItem("")
        self.comboBoxSOSIndex.addItem("")
        self.comboBoxSOSIndex.addItem("")
        self.comboBoxSOSIndex.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxSOSIndex, 0, 0, 1, 1)
        self.groupBoxSOS = QtWidgets.QGroupBox(self.tabSOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSOS.sizePolicy().hasHeightForWidth())
        self.groupBoxSOS.setSizePolicy(sizePolicy)
        self.groupBoxSOS.setObjectName("groupBoxSOS")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxSOS)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonSOSUpdate = QtWidgets.QPushButton(self.groupBoxSOS)
        self.pushButtonSOSUpdate.setEnabled(False)
        self.pushButtonSOSUpdate.setObjectName("pushButtonSOSUpdate")
        self.gridLayout_5.addWidget(self.pushButtonSOSUpdate, 0, 0, 1, 1)
        self.pushButtonSOSReset = QtWidgets.QPushButton(self.groupBoxSOS)
        self.pushButtonSOSReset.setEnabled(False)
        self.pushButtonSOSReset.setObjectName("pushButtonSOSReset")
        self.gridLayout_5.addWidget(self.pushButtonSOSReset, 0, 1, 1, 1)
        self.labelSOSInitialSeed = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSInitialSeed.setObjectName("labelSOSInitialSeed")
        self.gridLayout_5.addWidget(self.labelSOSInitialSeed, 1, 0, 1, 1)
        self.lineEditSOSInitialSeed = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSInitialSeed.setMaxLength(8)
        self.lineEditSOSInitialSeed.setReadOnly(True)
        self.lineEditSOSInitialSeed.setObjectName("lineEditSOSInitialSeed")
        self.gridLayout_5.addWidget(self.lineEditSOSInitialSeed, 1, 1, 1, 1)
        self.labelSOSCurrentSeed = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSCurrentSeed.setObjectName("labelSOSCurrentSeed")
        self.gridLayout_5.addWidget(self.labelSOSCurrentSeed, 2, 0, 1, 1)
        self.lineEditSOSCurrentSeed = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSCurrentSeed.setMaxLength(8)
        self.lineEditSOSCurrentSeed.setReadOnly(True)
        self.lineEditSOSCurrentSeed.setObjectName("lineEditSOSCurrentSeed")
        self.gridLayout_5.addWidget(self.lineEditSOSCurrentSeed, 2, 1, 1, 1)
        self.labelSOSFrame = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSFrame.setObjectName("labelSOSFrame")
        self.gridLayout_5.addWidget(self.labelSOSFrame, 3, 0, 1, 1)
        self.lineEditSOSFrame = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSFrame.setMaxLength(8)
        self.lineEditSOSFrame.setReadOnly(True)
        self.lineEditSOSFrame.setObjectName("lineEditSOSFrame")
        self.gridLayout_5.addWidget(self.lineEditSOSFrame, 3, 1, 1, 1)
        self.labelSOSChainCount = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSChainCount.setObjectName("labelSOSChainCount")
        self.gridLayout_5.addWidget(self.labelSOSChainCount, 4, 0, 1, 1)
        self.lineEditSOSChainCount = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSChainCount.setMaxLength(8)
        self.lineEditSOSChainCount.setReadOnly(True)
        self.lineEditSOSChainCount.setObjectName("lineEditSOSChainCount")
        self.gridLayout_5.addWidget(self.lineEditSOSChainCount, 4, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxSOS, 0, 1, 2, 1)
        self.sosPokemon = PokemonDisplay(self.tabSOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sosPokemon.sizePolicy().hasHeightForWidth())
        self.sosPokemon.setSizePolicy(sizePolicy)
        self.sosPokemon.setObjectName("sosPokemon")
        self.gridLayout_8.addWidget(self.sosPokemon, 1, 0, 1, 1)
        self.tabWidgetGen7.addTab(self.tabSOS, "")
        self.gridLayout_12.addWidget(self.tabWidgetGen7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGen7, "")
        self.gridLayout_10.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "CitraRNG 3.0.0", None, -1))
        self.groupBoxConnection.setTitle(QtWidgets.QApplication.translate("MainWindow", "Connection", None, -1))
        self.pushButtonConnect.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.labelUpdateDelay.setText(QtWidgets.QApplication.translate("MainWindow", "Auto update delay(seconds):", None, -1))
        self.labelStatus.setText(QtWidgets.QApplication.translate("MainWindow", "Status: Not Connected", None, -1))
        self.comboBoxGameSelection.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "XY", None, -1))
        self.comboBoxGameSelection.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "ORAS", None, -1))
        self.comboBoxGameSelection.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "SM", None, -1))
        self.comboBoxGameSelection.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "USUM", None, -1))
        self.comboBoxMainIndex6.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Party 1", None, -1))
        self.comboBoxMainIndex6.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Party 2", None, -1))
        self.comboBoxMainIndex6.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Party 3", None, -1))
        self.comboBoxMainIndex6.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Party 4", None, -1))
        self.comboBoxMainIndex6.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Party 5", None, -1))
        self.comboBoxMainIndex6.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Party 6", None, -1))
        self.comboBoxMainIndex6.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Wild", None, -1))
        self.groupBoxMainRNG6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Main RNG", None, -1))
        self.labelTiny2.setText(QtWidgets.QApplication.translate("MainWindow", "[2]", None, -1))
        self.labelTiny0.setText(QtWidgets.QApplication.translate("MainWindow", "[0]", None, -1))
        self.labelTiny3.setText(QtWidgets.QApplication.translate("MainWindow", "[3]", None, -1))
        self.labelTiny1.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.labelMainCurrentSeed6.setText(QtWidgets.QApplication.translate("MainWindow", "Current Seed:", None, -1))
        self.labelMainInitialSeed6.setText(QtWidgets.QApplication.translate("MainWindow", "Initial Seed:", None, -1))
        self.labelMainFrame6.setText(QtWidgets.QApplication.translate("MainWindow", "Frame:", None, -1))
        self.pushButtonMainUpdate6.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.labelSaveVariable.setText(QtWidgets.QApplication.translate("MainWindow", "Save Variable:", None, -1))
        self.tabWidgetGen6.setTabText(self.tabWidgetGen6.indexOf(self.tabMain6), QtWidgets.QApplication.translate("MainWindow", "Main", None, -1))
        self.groupBoxEggRNG6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Egg RNG", None, -1))
        self.labelEggReady6.setText(QtWidgets.QApplication.translate("MainWindow", "Egg Ready:", None, -1))
        self.labelEggReadyStatus6.setText(QtWidgets.QApplication.translate("MainWindow", "No egg yet", None, -1))
        self.pushButtonEggUpdate6.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.labelEggSeed0_6.setText(QtWidgets.QApplication.translate("MainWindow", "[0]", None, -1))
        self.labelEggSeed1_6.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.tabWidgetGen6.setTabText(self.tabWidgetGen6.indexOf(self.tabEgg6), QtWidgets.QApplication.translate("MainWindow", "Egg", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGen6), QtWidgets.QApplication.translate("MainWindow", "Gen 6", None, -1))
        self.comboBoxMainIndex7.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Party 1", None, -1))
        self.comboBoxMainIndex7.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Party 2", None, -1))
        self.comboBoxMainIndex7.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Party 3", None, -1))
        self.comboBoxMainIndex7.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Party 4", None, -1))
        self.comboBoxMainIndex7.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Party 5", None, -1))
        self.comboBoxMainIndex7.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Party 6", None, -1))
        self.comboBoxMainIndex7.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Wild", None, -1))
        self.groupBoxMainRNG7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Main RNG", None, -1))
        self.labelMainInitialSeed7.setText(QtWidgets.QApplication.translate("MainWindow", "Initial Seed:", None, -1))
        self.labelMainCurrentSeed7.setText(QtWidgets.QApplication.translate("MainWindow", "Current Seed:", None, -1))
        self.labelMainFrame7.setText(QtWidgets.QApplication.translate("MainWindow", "Frame:", None, -1))
        self.pushButtonMainUpdate7.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.tabWidgetGen7.setTabText(self.tabWidgetGen7.indexOf(self.tabMain7), QtWidgets.QApplication.translate("MainWindow", "Main", None, -1))
        self.groupBoxEggRNG7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Egg RNG", None, -1))
        self.pushButtonEggUpdate7.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.labelEggReady7.setText(QtWidgets.QApplication.translate("MainWindow", "Egg Ready:", None, -1))
        self.labelEggReadyStatus7.setText(QtWidgets.QApplication.translate("MainWindow", "No egg yet", None, -1))
        self.labelEggSeed3_7.setText(QtWidgets.QApplication.translate("MainWindow", "[3]", None, -1))
        self.labelEggSeed2_7.setText(QtWidgets.QApplication.translate("MainWindow", "[2]", None, -1))
        self.labelEggSeed1_7.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.labelEggSeed0_7.setText(QtWidgets.QApplication.translate("MainWindow", "[0]", None, -1))
        self.tabWidgetGen7.setTabText(self.tabWidgetGen7.indexOf(self.tabEgg7), QtWidgets.QApplication.translate("MainWindow", "Egg", None, -1))
        self.comboBoxSOSIndex.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "SOS 1", None, -1))
        self.comboBoxSOSIndex.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "SOS 2", None, -1))
        self.comboBoxSOSIndex.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "SOS 3", None, -1))
        self.comboBoxSOSIndex.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "SOS 4", None, -1))
        self.groupBoxSOS.setTitle(QtWidgets.QApplication.translate("MainWindow", "SOS RNG", None, -1))
        self.pushButtonSOSUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.pushButtonSOSReset.setToolTip(QtWidgets.QApplication.translate("MainWindow", "This should be used after a battle", None, -1))
        self.pushButtonSOSReset.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.labelSOSInitialSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Initial Seed:", None, -1))
        self.labelSOSCurrentSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Current Seed:", None, -1))
        self.labelSOSFrame.setText(QtWidgets.QApplication.translate("MainWindow", "Frame:", None, -1))
        self.labelSOSChainCount.setText(QtWidgets.QApplication.translate("MainWindow", "Chain Count:", None, -1))
        self.tabWidgetGen7.setTabText(self.tabWidgetGen7.indexOf(self.tabSOS), QtWidgets.QApplication.translate("MainWindow", "SOS", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGen7), QtWidgets.QApplication.translate("MainWindow", "Gen 7", None, -1))
