# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Sat Mar  2 13:33:25 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from PokemonDisplay import PokemonDisplay

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 640)
        MainWindow.setMinimumSize(QtCore.QSize(770, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxConnection = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxConnection.sizePolicy().hasHeightForWidth())
        self.groupBoxConnection.setSizePolicy(sizePolicy)
        self.groupBoxConnection.setObjectName("groupBoxConnection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxConnection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBoxConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConnect.sizePolicy().hasHeightForWidth())
        self.pushButtonConnect.setSizePolicy(sizePolicy)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayout_2.addWidget(self.pushButtonConnect, 0, 1, 1, 1)
        self.labelUpdateDelay = QtWidgets.QLabel(self.groupBoxConnection)
        self.labelUpdateDelay.setObjectName("labelUpdateDelay")
        self.gridLayout_2.addWidget(self.labelUpdateDelay, 1, 0, 1, 1)
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.groupBoxConnection)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.gridLayout_2.addWidget(self.pushButtonDisconnect, 0, 2, 1, 1)
        self.labelStatus = QtWidgets.QLabel(self.groupBoxConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout_2.addWidget(self.labelStatus, 1, 2, 1, 1)
        self.comboBoxGameSelection = QtWidgets.QComboBox(self.groupBoxConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxGameSelection.sizePolicy().hasHeightForWidth())
        self.comboBoxGameSelection.setSizePolicy(sizePolicy)
        self.comboBoxGameSelection.setObjectName("comboBoxGameSelection")
        self.comboBoxGameSelection.addItem("")
        self.comboBoxGameSelection.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxGameSelection, 0, 0, 1, 1)
        self.doubleSpinBoxDelay = QtWidgets.QDoubleSpinBox(self.groupBoxConnection)
        self.doubleSpinBoxDelay.setEnabled(False)
        self.doubleSpinBoxDelay.setMinimum(0.5)
        self.doubleSpinBoxDelay.setMaximum(2.0)
        self.doubleSpinBoxDelay.setObjectName("doubleSpinBoxDelay")
        self.gridLayout_2.addWidget(self.doubleSpinBoxDelay, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBoxConnection, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabMain)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBoxMainIndex = QtWidgets.QComboBox(self.tabMain)
        self.comboBoxMainIndex.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMainIndex.sizePolicy().hasHeightForWidth())
        self.comboBoxMainIndex.setSizePolicy(sizePolicy)
        self.comboBoxMainIndex.setObjectName("comboBoxMainIndex")
        self.comboBoxMainIndex.addItem("")
        self.comboBoxMainIndex.addItem("")
        self.comboBoxMainIndex.addItem("")
        self.comboBoxMainIndex.addItem("")
        self.comboBoxMainIndex.addItem("")
        self.comboBoxMainIndex.addItem("")
        self.comboBoxMainIndex.addItem("")
        self.gridLayout_7.addWidget(self.comboBoxMainIndex, 0, 0, 1, 1)
        self.groupBoxMainRNG = QtWidgets.QGroupBox(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMainRNG.sizePolicy().hasHeightForWidth())
        self.groupBoxMainRNG.setSizePolicy(sizePolicy)
        self.groupBoxMainRNG.setObjectName("groupBoxMainRNG")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBoxMainRNG)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButtonMainUpdate = QtWidgets.QPushButton(self.groupBoxMainRNG)
        self.pushButtonMainUpdate.setEnabled(False)
        self.pushButtonMainUpdate.setObjectName("pushButtonMainUpdate")
        self.gridLayout_10.addWidget(self.pushButtonMainUpdate, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelMainInitialSeed = QtWidgets.QLabel(self.groupBoxMainRNG)
        self.labelMainInitialSeed.setObjectName("labelMainInitialSeed")
        self.gridLayout_3.addWidget(self.labelMainInitialSeed, 0, 0, 1, 1)
        self.lineEditMainInitialSeed = QtWidgets.QLineEdit(self.groupBoxMainRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMainInitialSeed.sizePolicy().hasHeightForWidth())
        self.lineEditMainInitialSeed.setSizePolicy(sizePolicy)
        self.lineEditMainInitialSeed.setMaxLength(8)
        self.lineEditMainInitialSeed.setReadOnly(True)
        self.lineEditMainInitialSeed.setObjectName("lineEditMainInitialSeed")
        self.gridLayout_3.addWidget(self.lineEditMainInitialSeed, 0, 1, 1, 1)
        self.labelMainCurrentSeed = QtWidgets.QLabel(self.groupBoxMainRNG)
        self.labelMainCurrentSeed.setObjectName("labelMainCurrentSeed")
        self.gridLayout_3.addWidget(self.labelMainCurrentSeed, 1, 0, 1, 1)
        self.lineEditMainCurrentSeed = QtWidgets.QLineEdit(self.groupBoxMainRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMainCurrentSeed.sizePolicy().hasHeightForWidth())
        self.lineEditMainCurrentSeed.setSizePolicy(sizePolicy)
        self.lineEditMainCurrentSeed.setMaxLength(16)
        self.lineEditMainCurrentSeed.setReadOnly(True)
        self.lineEditMainCurrentSeed.setObjectName("lineEditMainCurrentSeed")
        self.gridLayout_3.addWidget(self.lineEditMainCurrentSeed, 1, 1, 1, 1)
        self.labelMainFrame = QtWidgets.QLabel(self.groupBoxMainRNG)
        self.labelMainFrame.setObjectName("labelMainFrame")
        self.gridLayout_3.addWidget(self.labelMainFrame, 2, 0, 1, 1)
        self.lineEditMainFrame = QtWidgets.QLineEdit(self.groupBoxMainRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMainFrame.sizePolicy().hasHeightForWidth())
        self.lineEditMainFrame.setSizePolicy(sizePolicy)
        self.lineEditMainFrame.setReadOnly(True)
        self.lineEditMainFrame.setObjectName("lineEditMainFrame")
        self.gridLayout_3.addWidget(self.lineEditMainFrame, 2, 1, 1, 1)
        self.labelMainTSV = QtWidgets.QLabel(self.groupBoxMainRNG)
        self.labelMainTSV.setObjectName("labelMainTSV")
        self.gridLayout_3.addWidget(self.labelMainTSV, 3, 0, 1, 1)
        self.lineEditMainTSV = QtWidgets.QLineEdit(self.groupBoxMainRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMainTSV.sizePolicy().hasHeightForWidth())
        self.lineEditMainTSV.setSizePolicy(sizePolicy)
        self.lineEditMainTSV.setMaxLength(4)
        self.lineEditMainTSV.setReadOnly(True)
        self.lineEditMainTSV.setObjectName("lineEditMainTSV")
        self.gridLayout_3.addWidget(self.lineEditMainTSV, 3, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBoxMainRNG, 0, 1, 2, 1)
        self.mainPokemon = PokemonDisplay(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPokemon.sizePolicy().hasHeightForWidth())
        self.mainPokemon.setSizePolicy(sizePolicy)
        self.mainPokemon.setObjectName("mainPokemon")
        self.gridLayout_7.addWidget(self.mainPokemon, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, "")
        self.tabEgg = QtWidgets.QWidget()
        self.tabEgg.setObjectName("tabEgg")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabEgg)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBoxEggRNG = QtWidgets.QGroupBox(self.tabEgg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEggRNG.sizePolicy().hasHeightForWidth())
        self.groupBoxEggRNG.setSizePolicy(sizePolicy)
        self.groupBoxEggRNG.setObjectName("groupBoxEggRNG")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxEggRNG)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButtonEggUpdate = QtWidgets.QPushButton(self.groupBoxEggRNG)
        self.pushButtonEggUpdate.setEnabled(False)
        self.pushButtonEggUpdate.setObjectName("pushButtonEggUpdate")
        self.gridLayout_11.addWidget(self.pushButtonEggUpdate, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelEggReady = QtWidgets.QLabel(self.groupBoxEggRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEggReady.sizePolicy().hasHeightForWidth())
        self.labelEggReady.setSizePolicy(sizePolicy)
        self.labelEggReady.setObjectName("labelEggReady")
        self.gridLayout_4.addWidget(self.labelEggReady, 0, 0, 1, 1)
        self.labelEggReadyStatus = QtWidgets.QLabel(self.groupBoxEggRNG)
        self.labelEggReadyStatus.setObjectName("labelEggReadyStatus")
        self.gridLayout_4.addWidget(self.labelEggReadyStatus, 0, 1, 1, 1)
        self.labelEggSeed3 = QtWidgets.QLabel(self.groupBoxEggRNG)
        self.labelEggSeed3.setObjectName("labelEggSeed3")
        self.gridLayout_4.addWidget(self.labelEggSeed3, 1, 0, 1, 1)
        self.lineEditEggSeed3 = QtWidgets.QLineEdit(self.groupBoxEggRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed3.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed3.setSizePolicy(sizePolicy)
        self.lineEditEggSeed3.setMaxLength(8)
        self.lineEditEggSeed3.setReadOnly(True)
        self.lineEditEggSeed3.setObjectName("lineEditEggSeed3")
        self.gridLayout_4.addWidget(self.lineEditEggSeed3, 1, 1, 1, 1)
        self.labelEggSeed2 = QtWidgets.QLabel(self.groupBoxEggRNG)
        self.labelEggSeed2.setObjectName("labelEggSeed2")
        self.gridLayout_4.addWidget(self.labelEggSeed2, 2, 0, 1, 1)
        self.lineEditEggSeed2 = QtWidgets.QLineEdit(self.groupBoxEggRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed2.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed2.setSizePolicy(sizePolicy)
        self.lineEditEggSeed2.setMaxLength(8)
        self.lineEditEggSeed2.setReadOnly(True)
        self.lineEditEggSeed2.setObjectName("lineEditEggSeed2")
        self.gridLayout_4.addWidget(self.lineEditEggSeed2, 2, 1, 1, 1)
        self.labelEggSeed1 = QtWidgets.QLabel(self.groupBoxEggRNG)
        self.labelEggSeed1.setObjectName("labelEggSeed1")
        self.gridLayout_4.addWidget(self.labelEggSeed1, 3, 0, 1, 1)
        self.lineEditEggSeed1 = QtWidgets.QLineEdit(self.groupBoxEggRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed1.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed1.setSizePolicy(sizePolicy)
        self.lineEditEggSeed1.setMaxLength(8)
        self.lineEditEggSeed1.setReadOnly(True)
        self.lineEditEggSeed1.setObjectName("lineEditEggSeed1")
        self.gridLayout_4.addWidget(self.lineEditEggSeed1, 3, 1, 1, 1)
        self.labelEggSeed0 = QtWidgets.QLabel(self.groupBoxEggRNG)
        self.labelEggSeed0.setObjectName("labelEggSeed0")
        self.gridLayout_4.addWidget(self.labelEggSeed0, 4, 0, 1, 1)
        self.lineEditEggSeed0 = QtWidgets.QLineEdit(self.groupBoxEggRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEggSeed0.sizePolicy().hasHeightForWidth())
        self.lineEditEggSeed0.setSizePolicy(sizePolicy)
        self.lineEditEggSeed0.setMaxLength(8)
        self.lineEditEggSeed0.setReadOnly(True)
        self.lineEditEggSeed0.setObjectName("lineEditEggSeed0")
        self.gridLayout_4.addWidget(self.lineEditEggSeed0, 4, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBoxEggRNG, 0, 2, 2, 1)
        self.eggParent1 = PokemonDisplay(self.tabEgg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eggParent1.sizePolicy().hasHeightForWidth())
        self.eggParent1.setSizePolicy(sizePolicy)
        self.eggParent1.setObjectName("eggParent1")
        self.gridLayout_6.addWidget(self.eggParent1, 0, 0, 2, 1)
        self.eggParent2 = PokemonDisplay(self.tabEgg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eggParent2.sizePolicy().hasHeightForWidth())
        self.eggParent2.setSizePolicy(sizePolicy)
        self.eggParent2.setObjectName("eggParent2")
        self.gridLayout_6.addWidget(self.eggParent2, 0, 1, 2, 1)
        self.tabWidget.addTab(self.tabEgg, "")
        self.tabSOS = QtWidgets.QWidget()
        self.tabSOS.setObjectName("tabSOS")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabSOS)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBoxSOSIndex = QtWidgets.QComboBox(self.tabSOS)
        self.comboBoxSOSIndex.setEnabled(False)
        self.comboBoxSOSIndex.setObjectName("comboBoxSOSIndex")
        self.comboBoxSOSIndex.addItem("")
        self.comboBoxSOSIndex.addItem("")
        self.comboBoxSOSIndex.addItem("")
        self.comboBoxSOSIndex.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxSOSIndex, 0, 0, 1, 1)
        self.groupBoxSOS = QtWidgets.QGroupBox(self.tabSOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSOS.sizePolicy().hasHeightForWidth())
        self.groupBoxSOS.setSizePolicy(sizePolicy)
        self.groupBoxSOS.setObjectName("groupBoxSOS")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxSOS)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButtonSOSUpdate = QtWidgets.QPushButton(self.groupBoxSOS)
        self.pushButtonSOSUpdate.setEnabled(False)
        self.pushButtonSOSUpdate.setObjectName("pushButtonSOSUpdate")
        self.gridLayout_9.addWidget(self.pushButtonSOSUpdate, 0, 0, 1, 1)
        self.pushButtonSOSReset = QtWidgets.QPushButton(self.groupBoxSOS)
        self.pushButtonSOSReset.setEnabled(False)
        self.pushButtonSOSReset.setObjectName("pushButtonSOSReset")
        self.gridLayout_9.addWidget(self.pushButtonSOSReset, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelSOSInitialSeed = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSInitialSeed.setObjectName("labelSOSInitialSeed")
        self.gridLayout_5.addWidget(self.labelSOSInitialSeed, 0, 0, 1, 1)
        self.lineEditSOSInitialSeed = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSInitialSeed.setMaxLength(8)
        self.lineEditSOSInitialSeed.setReadOnly(True)
        self.lineEditSOSInitialSeed.setObjectName("lineEditSOSInitialSeed")
        self.gridLayout_5.addWidget(self.lineEditSOSInitialSeed, 0, 1, 1, 1)
        self.labelSOSCurrentSeed = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSCurrentSeed.setObjectName("labelSOSCurrentSeed")
        self.gridLayout_5.addWidget(self.labelSOSCurrentSeed, 1, 0, 1, 1)
        self.lineEditSOSCurrentSeed = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSCurrentSeed.setMaxLength(8)
        self.lineEditSOSCurrentSeed.setReadOnly(True)
        self.lineEditSOSCurrentSeed.setObjectName("lineEditSOSCurrentSeed")
        self.gridLayout_5.addWidget(self.lineEditSOSCurrentSeed, 1, 1, 1, 1)
        self.labelSOSFrame = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSFrame.setObjectName("labelSOSFrame")
        self.gridLayout_5.addWidget(self.labelSOSFrame, 2, 0, 1, 1)
        self.lineEditSOSFrame = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSFrame.setMaxLength(8)
        self.lineEditSOSFrame.setReadOnly(True)
        self.lineEditSOSFrame.setObjectName("lineEditSOSFrame")
        self.gridLayout_5.addWidget(self.lineEditSOSFrame, 2, 1, 1, 1)
        self.labelSOSChainCount = QtWidgets.QLabel(self.groupBoxSOS)
        self.labelSOSChainCount.setObjectName("labelSOSChainCount")
        self.gridLayout_5.addWidget(self.labelSOSChainCount, 3, 0, 1, 1)
        self.lineEditSOSChainCount = QtWidgets.QLineEdit(self.groupBoxSOS)
        self.lineEditSOSChainCount.setMaxLength(8)
        self.lineEditSOSChainCount.setReadOnly(True)
        self.lineEditSOSChainCount.setObjectName("lineEditSOSChainCount")
        self.gridLayout_5.addWidget(self.lineEditSOSChainCount, 3, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBoxSOS, 0, 1, 2, 1)
        self.sosPokemon = PokemonDisplay(self.tabSOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sosPokemon.sizePolicy().hasHeightForWidth())
        self.sosPokemon.setSizePolicy(sizePolicy)
        self.sosPokemon.setObjectName("sosPokemon")
        self.gridLayout_8.addWidget(self.sosPokemon, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabSOS, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "CitraRNG 1.2.3", None, -1))
        self.groupBoxConnection.setTitle(QtWidgets.QApplication.translate("MainWindow", "Connection", None, -1))
        self.pushButtonConnect.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.labelUpdateDelay.setText(QtWidgets.QApplication.translate("MainWindow", "Auto update delay(seconds):", None, -1))
        self.pushButtonDisconnect.setText(QtWidgets.QApplication.translate("MainWindow", "Disconnect", None, -1))
        self.labelStatus.setText(QtWidgets.QApplication.translate("MainWindow", "Status: Not Connected", None, -1))
        self.comboBoxGameSelection.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Sun/Moon", None, -1))
        self.comboBoxGameSelection.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Ultra Sun/Ultra Moon", None, -1))
        self.comboBoxMainIndex.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Party 1", None, -1))
        self.comboBoxMainIndex.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Party 2", None, -1))
        self.comboBoxMainIndex.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Party 3", None, -1))
        self.comboBoxMainIndex.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Party 4", None, -1))
        self.comboBoxMainIndex.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Party 5", None, -1))
        self.comboBoxMainIndex.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Party 6", None, -1))
        self.comboBoxMainIndex.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Wild", None, -1))
        self.groupBoxMainRNG.setTitle(QtWidgets.QApplication.translate("MainWindow", "Main RNG", None, -1))
        self.pushButtonMainUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.labelMainInitialSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Initial Seed:", None, -1))
        self.labelMainCurrentSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Current Seed:", None, -1))
        self.labelMainFrame.setText(QtWidgets.QApplication.translate("MainWindow", "Frame:", None, -1))
        self.labelMainTSV.setText(QtWidgets.QApplication.translate("MainWindow", "TSV:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), QtWidgets.QApplication.translate("MainWindow", "Main", None, -1))
        self.groupBoxEggRNG.setTitle(QtWidgets.QApplication.translate("MainWindow", "Egg RNG", None, -1))
        self.pushButtonEggUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.labelEggReady.setText(QtWidgets.QApplication.translate("MainWindow", "Egg Ready:", None, -1))
        self.labelEggReadyStatus.setText(QtWidgets.QApplication.translate("MainWindow", "No egg yet", None, -1))
        self.labelEggSeed3.setText(QtWidgets.QApplication.translate("MainWindow", "[3]", None, -1))
        self.labelEggSeed2.setText(QtWidgets.QApplication.translate("MainWindow", "[2]", None, -1))
        self.labelEggSeed1.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.labelEggSeed0.setText(QtWidgets.QApplication.translate("MainWindow", "[0]", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEgg), QtWidgets.QApplication.translate("MainWindow", "Egg", None, -1))
        self.comboBoxSOSIndex.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "SOS 1", None, -1))
        self.comboBoxSOSIndex.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "SOS 2", None, -1))
        self.comboBoxSOSIndex.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "SOS 3", None, -1))
        self.comboBoxSOSIndex.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "SOS 4", None, -1))
        self.groupBoxSOS.setTitle(QtWidgets.QApplication.translate("MainWindow", "SOS RNG", None, -1))
        self.pushButtonSOSUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.pushButtonSOSReset.setToolTip(QtWidgets.QApplication.translate("MainWindow", "This should be used after a battle", None, -1))
        self.pushButtonSOSReset.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.labelSOSInitialSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Initial Seed:", None, -1))
        self.labelSOSCurrentSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Current Seed:", None, -1))
        self.labelSOSFrame.setText(QtWidgets.QApplication.translate("MainWindow", "Frame:", None, -1))
        self.labelSOSChainCount.setText(QtWidgets.QApplication.translate("MainWindow", "Chain Count:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSOS), QtWidgets.QApplication.translate("MainWindow", "SOS", None, -1))
